"""Initial migration

Revision ID: 207e72951222
Revises: 
Create Date: 2026-01-30 18:55:13.540913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207e72951222'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obz_justificativas', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        batch_op.alter_column('valor_orcado',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=False)
        batch_op.alter_column('data_atualizacao',
                   existing_type=sa.TIMESTAMP(),
                   type_=sa.DateTime(),
                   existing_nullable=True,
                   existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_obz_centro')
        batch_op.create_index(batch_op.f('ix_obz_justificativas_centro_gasto_codigo'), ['centro_gasto_codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obz_justificativas_centro_gasto_codigo'), table_name='obz_justificativas')
    op.create_index(op.f('idx_obz_centro'), 'obz_justificativas', ['centro_gasto_codigo'], unique=False)
    op.alter_column('obz_justificativas', 'data_atualizacao',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('obz_justificativas', 'valor_orcado',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('obz_justificativas', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
