"""Add regional and base columns

Revision ID: 9941750a2837
Revises: e728139563fb
Create Date: 2026-02-04 11:55:17.542955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9941750a2837'
down_revision: Union[str, Sequence[str], None] = 'e728139563fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos_realizados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regional', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('base', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_lancamentos_realizados_base'), ['base'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_realizados_regional'), ['regional'], unique=False)

    with op.batch_alter_table('provisoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regional', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('base', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provisoes', schema=None) as batch_op:
        batch_op.drop_column('base')
        batch_op.drop_column('regional')

    with op.batch_alter_table('lancamentos_realizados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_realizados_regional'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_realizados_base'))
        batch_op.drop_column('base')
        batch_op.drop_column('regional')

    # ### end Alembic commands ###
